### ISSUE TITLE
Derivation formatter is broken (segfault / no-op)

### ISSUE THREAD

**Issue by dlukes** [ufal/morphodita#16]
When I try to retrieve derivations using the `run_morpho_analyze` CLI tool, I get a segfault. E.g. with this command:

```sh
echo přijít | ./run_morpho_analyze --from_tagger --derivation=root czech-morfflex-pdt-161115.tagger 1
```

When I try to do so through the Python bindings (assuming the script below uses them correctly...), there's no segfault, but there's no derivation either, it's basically a no-op:

```python
from ufal.morphodita import *
df = DerivationFormatter.newRootDerivationFormatter(
    Tagger.load("czech-morfflex-pdt-161115.tagger").getMorpho().getDerivator()
)
print(df.formatDerivation("přijít"))
```

This just prints `přijít`. (If that's the expected output, then derivation probably means something else than I think it does ;) )

**Comment by foxik** [comment]
Thanks! The crash was just fixed in #7683f99.

The second result (that "přijít" does not change on derivation) is unfortunately correct. On https://lindat.mff.cuni.cz/services/morphodita/ , choose "Append whole derivation tree" option and run Tag/Analyze on "přijít" -- you will see that it is in fact a root of a tree.

This is caused by Derinet from 2016 where many of derivation links are missing. The good news is that current Derinet is much more complete, see https://ufal.mff.cuni.cz/derinet/derinet-search?ds_q=p%C5%99ij%C3%ADt&ds_defA=lemma&ds_db=%2F~vidra%2Fderinet%2Fsearch%2FUDer-1.0-cs-DeriNet-fmt1.tsv&ds_style=circ&ds_limit=10 for a tree with "přijít" which is much much better.

We hope to release a new MorphoDiTa model for the newly-released PDT-C 1.0; that will of course also contain the new Derinet... So stay tuned ;-)

**Comment by dlukes** [comment]
Ah, gotcha, thanks! :) It did seem weird that the same underlying issue would lead to a segfault in one case and not in the other, but as I'd been checking on-line against the current version of DeriNet which did show a derivation for *přijít* (as you've linked), I thought it must also be a bug. Now it makes sense.

> So stay tuned ;-)

Sounds great! Any feed I can subscribe to in order to be notified when that happens?

**Comment by foxik** [comment]
> Sounds great! Any feed I can subscribe to in order to be notified when that happens?

Unfortunately nothing specific. But the documentation here in this repository (in the `doc` dir) will be updated, so you could watch pulls to this repo (there are very few of them anyway :-)

**Comment by dlukes** [comment]
Thanks, done :) Will that send notifications for regular commits though? [You don't seem to use actual PRs all that much](https://github.com/ufal/morphodita/pulls) (which makes sense, why would you when you write all the code yourself).

It looks like GitHub also provides Atom feeds for all commits to a branch, e.g. <https://github.com/ufal/morphodita/commits/master.atom>. So I've also subscribed to that (via <https://blogtrottr.com/>, if anyone else is interested).

At any rate, I usually check the MorphoDiTa docs every now and then for new models anyway, so I'll find out eventually :)
