### ISSUE TITLE
Endpoint `tag` returns `spaces` in result_object

### ISSUE THREAD

**Issue by martcernycsob** [ufal/morphodita#20]
Endpoint `tag` returns result_object with `spaces` instead of `space`. This is not mentioned in doc https://lindat.mff.cuni.cz/services/morphodita/api-reference.php#tag

Url to reproduce: http://lindat.mff.cuni.cz/services/morphodita/api/tag?output=json&model=czech-morfflex&data=.4.+&guesser=no

Response
```json
{
  "model": "czech-morfflex-pdt-161115",
  "acknowledgements": [
    "http://ufal.mff.cuni.cz/morphodita#morphodita_acknowledgements",
    "http://ufal.mff.cuni.cz/morphodita/users-manual#czech-morfflex-pdt_acknowledgements"
  ],
  "result": [
    [
      { "token": ".", "lemma": ".", "tag": "Z:-------------" },
      { "token": "4", "lemma": "4", "tag": "C=-------------" },
      { "token": ".", "lemma": ".", "tag": "Z:-------------", "spaces": " " }
    ]
  ]
}
```

**Comment by foxik** [comment]
Hi,

thanks for reporting, you are right. The server has been returning `spaces` since the original implementation, so I just updated the documentation (which claimed the key is `space`) to also use `spaces`.

Note that this was true not just for `tag`, but also for `analyze` and `tokenize`.

Cheers!

**Comment by martcernycsob** [comment]
Thanks for quick reply. This solution is not enough. For https://lindat.mff.cuni.cz/services/morphodita/api/tag?output=json&model=czech-morfflex&data=4+5&guesser=no the parameter is `space` instead of `spaces`.

**Comment by foxik** [comment]
Ouch, sorry. I glanced through the implementation and saw that we return "spaces" there -- but we return both "spaces" and "space" inconsistently.

Because we returned mostly "space" (the "spaces" was returned only on the last token), I kept "space" as the official name, I reverted the documentation change, and commited a fix to the REST server. The LINDAT service has just been upgraded.
